services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      # Usando a sintaxe de valor padrão aqui também por consistência
      MYSQL_DATABASE: ${DB_NAME:-reparaai}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-senha}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reparai-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "${PORT:-3000}:3000" # Mapeia a porta do .env ou a padrão 3000
    depends_on:
      db:
        condition: service_healthy
    
    # MUDANÇA PRINCIPAL AQUI: Adicionamos os valores padrão
    environment:
      - PORT=${PORT:-3000}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-senha}
      - DB_NAME=${DB_NAME:-reparaai}
      - GOOGLE_KEY=${GOOGLE_KEY}
      - JWT_SECRET=${JWT_SECRET:-este_e_um_segredo_muito_seguro_para_o_reparaai}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}

    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - reparai-net

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "${VITE_PORT:-5174}:5173" # Adicionamos um padrão aqui também
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - reparai-net
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host", "--port", "5173"]

volumes:
  db_data:

networks:
  reparai-net:
    driver: bridge